export const AppErrorCode = {
  MOVEMENT_NAME_REQUIRED: 'MOVEMENT_NAME_REQUIRED',
  MOVEMENT_AMOUNT_INVALID: 'MOVEMENT_AMOUNT_INVALID',
  MOVEMENT_DATE_INVALID: 'MOVEMENT_DATE_INVALID',
  MOVEMENT_CATEGORY_REQUIRED: 'MOVEMENT_CATEGORY_REQUIRED',
  MOVEMENT_ENVELOPE_REQUIRED: 'MOVEMENT_ENVELOPE_REQUIRED',
  MOVEMENT_ID_INVALID: 'MOVEMENT_ID_INVALID',
  CATEGORY_NAME_REQUIRED: 'CATEGORY_NAME_REQUIRED',
  CATEGORY_DELETE_DEFAULT: 'CATEGORY_DELETE_DEFAULT',
  CATEGORY_NO_DEFAULT: 'CATEGORY_NO_DEFAULT',
  ACCOUNT_NAME_REQUIRED: 'ACCOUNT_NAME_REQUIRED',
  ACCOUNT_DELETE_DEFAULT: 'ACCOUNT_DELETE_DEFAULT',
  ENVELOPE_NAME_REQUIRED: 'ENVELOPE_NAME_REQUIRED',
  ENVELOPE_ACCOUNT_REQUIRED: 'ENVELOPE_ACCOUNT_REQUIRED',
  ENVELOPE_UPDATE_DEFAULT: 'ENVELOPE_UPDATE_DEFAULT',
  ENVELOPE_DELETE_DEFAULT: 'ENVELOPE_DELETE_DEFAULT',
  ENVELOPE_NO_ACCOUNT: 'ENVELOPE_NO_ACCOUNT',
  ENVELOPE_ACCOUNT_NO_DEFAULT: 'ENVELOPE_ACCOUNT_NO_DEFAULT',
  ENVELOPE_NOT_FOUND: 'ENVELOPE_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  PERIODSUMMARY_NOT_FOUND: 'PERIODSUMMARY_NOT_FOUND',
  MOVEMENT_NOT_FOUND: 'MOVEMENT_NOT_FOUND',
  INCORRECT_PARAMETERS: 'INCORRECT_PARAMETERS',
  ENVELOPE_ORPHAN_DEFAULT: 'ENVELOPE_ORPHAN_DEFAULT',
  TAG_TYPE_REQUIRED: 'TAG_TYPE_REQUIRED',
  TAG_NAME_REQUIRED: 'TAG_NAME_REQUIRED',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  UNKNOWN: 'UNKNOWN',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];

export class AppError extends Error {
  constructor(public readonly code: AppErrorCode) {
    super(code);
  }
}
