export const Channels = {
  MOVEMENT_CREATE: 'movement:create',
  MOVEMENT_GET_ALL: 'movement:getAll',
  MOVEMENT_GET_BY_ID: 'movement:getById',
  MOVEMENT_UPDATE: 'movement:update',
  MOVEMENT_DELETE: 'movement:delete',
  MOVEMENT_DELETE_MANY: 'movement:deleteMany',
  MOVEMENT_CONFIRM: 'movement:confirm',
  MOVEMENT_SUGGEST_NAMES: 'movement:suggestNames',
  MOVEMENT_GET_FILTER_SUMMARY: 'movement:getFilterSummary',

  PERIODIC_CREATE: 'periodic:create',
  PERIODIC_GET_ALL: 'periodic:getAll',
  PERIODIC_GET_BY_ID: 'periodic:getById',
  PERIODIC_GET_TAGS: 'periodic:getTags',
  PERIODIC_UPDATE: 'periodic:update',
  PERIODIC_DELETE: 'periodic:delete',
  PERIODIC_SET_ACTIVE: 'periodic:setActive',
  PERIODIC_RUN_DUE: 'periodic:runDue',
  PERIODIC_INSTANTIATE_CURRENT: 'periodic:instantiateCurrent',
  PERIODIC_CREATE_ADDITIONAL: 'periodic:createAdditional',

  TRANSFER_CREATE: 'transfer:create',
  TRANSFER_GET_ALL: 'transfer:getAll',
  TRANSFER_GET_FOR_ENVELOPE: 'transfer:getForEnvelope',
  TRANSFER_DELETE: 'transfer:delete',

  COMPOUND_CREATE: 'compound:create',
  COMPOUND_GET_ALL: 'compound:getAll',
  COMPOUND_GET_BY_ID: 'compound:getById',
  COMPOUND_GET_CHILDREN: 'compound:getChildren',
  COMPOUND_ADD_MEMBER: 'compound:addMember',
  COMPOUND_CREATE_MEMBER: 'compound:createMember',
  COMPOUND_REMOVE_MEMBER: 'compound:removeMember',
  COMPOUND_UPDATE: 'compound:update',
  COMPOUND_DELETE: 'compound:delete',

  CATEGORY_CREATE: 'category:create',
  CATEGORY_GET_ALL: 'category:getAll',
  CATEGORY_GET_BY_ID: 'category:getById',
  CATEGORY_UPDATE: 'category:update',
  CATEGORY_DELETE: 'category:delete',
  CATEGORY_SET_DEFAULT: 'category:setDefault',

  ACCOUNT_CREATE: 'account:create',
  ACCOUNT_GET_ALL: 'account:getAll',
  ACCOUNT_GET_BY_ID: 'account:getById',
  ACCOUNT_UPDATE: 'account:update',
  ACCOUNT_DELETE: 'account:delete',
  ACCOUNT_SET_DEFAULT: 'account:setDefault',
  ACCOUNT_GET_STATS: 'account:getStats',

  ENVELOPE_CREATE: 'envelope:create',
  ENVELOPE_GET_ALL: 'envelope:getAll',
  ENVELOPE_GET_BY_ID: 'envelope:getById',
  ENVELOPE_UPDATE: 'envelope:update',
  ENVELOPE_DELETE: 'envelope:delete',
  ENVELOPE_SET_DEFAULT: 'envelope:setDefault',

  TAG_CREATE: 'tag:create',
  TAG_GET_ALL: 'tag:getAll',
  TAG_GET_BY_ID: 'tag:getById',
  TAG_UPDATE: 'tag:update',
  TAG_DELETE: 'tag:delete',
  TAG_ADD_TO_MOVEMENT: 'tag:addToMovement',
  TAG_REMOVE_FROM_MOVEMENT: 'tag:removeFromMovement',
  TAG_GET_FOR_MOVEMENT: 'tag:getForMovement',
  TAG_GET_FOR_MOVEMENTS: 'tag:getForMovements',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',

  PERIOD_SUMMARY_CREATE: 'periodSummary:create',
  PERIOD_SUMMARY_UPSERT: 'periodSummary:upsert',
  PERIOD_SUMMARY_GET_ALL: 'periodSummary:getAll',
  PERIOD_SUMMARY_GET_LATEST: 'periodSummary:getLatest',
  PERIOD_SUMMARY_GET_BY_PERIOD: 'periodSummary:getByPeriod',
  PERIOD_SUMMARY_UPDATE: 'periodSummary:update',
  PERIOD_SUMMARY_DELETE: 'periodSummary:delete',

  IMPORT_EXPORT_PREVIEW: 'importExport:preview',
  IMPORT_EXPORT_COMMIT: 'importExport:commit',
  IMPORT_EXPORT_EXPORT: 'importExport:export',

  DB_BACKUP: 'database:backup',
  DB_RESTORE: 'database:restore',
  DB_DROP_ALL: 'database:dropAllTables',
  DB_SEED_EXAMPLE: 'database:seedExampleData',
} as const;
